spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true

    datasource:
        username: sa
        password:
        url: jdbc:h2:mem:task_manager;DB_CLOSE_DELAY=-1;MODE=PostgreSQL

    h2:
        console:
            enabled: true
            path: /h2

server:
    servlet:
        context-path: /api/v1
    port: 8085
